### ISSUE TITLE
Unable to determine projection from variable length records

### ISSUE THREAD

**Issue by jeffyamada** [johnfontaine/LasStreamReader#3]
Hey John,

Thanks for putting this together! I'm trying to consume some .las files (my first try at this). I'm just getting into working with this data so I really appreciate having a head start here with your reader!

I set up my system to config a 35meg file I got from USGS but I'm getting the below error. I saw you had a fix you committed for something similar. Wondering if you could shed some light on it. I'm happy to dig in myself and see if I can contribute a fix myself if I get that far!

Cheers!

`Error: Unable to determine projection from variable length records
    at LasStreamReader._do_read_vlr (/Users/jeff/dev/contours2/node_modules/LasStreamReader/src/las.js:203:40)
    at LasStreamReader._transform (/Users/jeff/dev/contours2/node_modules/LasStreamReader/src/las.js:136:18)
    at LasStreamReader.Transform._read (_stream_transform.js:186:10)
    at LasStreamReader.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:385:12)
    at writeOrBuffer (_stream_writable.js:371:5)
    at LasStreamReader.Writable.write (_stream_writable.js:288:11)
    at ReadStream.ondata (_stream_readable.js:642:20)
    at emitOne (events.js:115:13)
    at ReadStream.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at ReadStream.Readable.push (_stream_readable.js:211:10)
    at onread (fs.js:2003:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:664:17)`

**Comment by jeffyamada** [comment]
Ok - I just read the docs some more and saw that maybe I'd need to provide the EPSG code I found in the meta xml file provided (pasted below). 

`  const lasStream = new las.LasStreamReader({
    projection: {
      epsg_datsum: 26912,
    }
  });`

Didn't seem to do the trick though. Will keep digging!

`<?xml version="1.0" standalone="yes"?>
<Metadata>
<EntityID>UT_SaltLake_1x4m_2006_000403</EntityID>
<ProjectName>UT_SaltLake_1x4m_2006</ProjectName>
<ProjectMetadataFiles>http://dds.cr.usgs.gov/lidar_v2/UT/2006/UT_SaltLake_1x4m_2006/metadata/UT_SaltLake_1x4m_2006_metadata.zip</ProjectMetadataFiles>
<State>UT</State>
<BeginDate>2006-10-29</BeginDate>
<EndDate>2007-05-15</EndDate>
<VerticalDatum>NAVD88</VerticalDatum>
<MapProjection>UTM</MapProjection>
<MapZone>12</MapZone>
<MapProjectionDefinition>PROJCS["NAD_1983_UTM_Zone_12N",GEOGCS["GCS_North_American_1983",DATUM["D_North_American_1983",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",500000.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-111.0],PARAMETER["Scale_Factor",0.9996],PARAMETER["Latitude_Of_Origin",0.0],UNIT["Meter",1.0],AUTHORITY["EPSG",26912]]</MapProjectionDefinition>
<CenterLat>40.8009333</CenterLat>
<CenterLon>-111.8416860</CenterLon>
<ULLat>40.8098638</ULLat>
<ULLon>-111.8536666</ULLon>
<URLat>40.8100361</URLat>
<URLon>-111.8299332</URLon>
<LRLat>40.7920027</LRLat>
<LRLon>-111.8297082</LRLon>
<LLLat>40.7918305</LLLat>
<LLLon>-111.8534361</LLLon>
<MinX>428000.00</MinX>
<MaxX>429999.99</MaxX>
<MinY>4516000.00</MinY>
<MaxY>4517999.99</MaxY>
<MinZ>1538.62</MinZ>
<MaxZ>1950.98</MaxZ>
<VendorID>12tvl280160</VendorID>
<NumOfPulseRecords>4648543</NumOfPulseRecords>
<NumOfPulsesByReturn>(0) 4648543</NumOfPulsesByReturn>
<NumOfPtRecords>4648543</NumOfPtRecords>
<NumOfPtsByReturn>(1) 4648543</NumOfPtsByReturn>
<Intensity>0,0</Intensity>
<NominalPulseSpacing>0.927617</NominalPulseSpacing>
<PulseDensity>1.16215</PulseDensity>
<PulseDensityNPSUnits>METER</PulseDensityNPSUnits>
<VendorNominalPulseSpacing>1.4</VendorNominalPulseSpacing>
<VendorPointDensity>.7</VendorPointDensity>
<VendorPointDensityNPSUnits>METER</VendorPointDensityNPSUnits>
<FileFormat>las</FileFormat>
<LASVersion>1.2</LASVersion>
</Metadata>
`

**Comment by jeffyamada** [comment]
Got it! Looks like I didn't configure the projection option correctly, sorry for the noise! Hope to dig in more and contribute soon!
